RawGit is shutting down, replace it with jsDelivr
minos-org/minos-static pull request #13
Opened 2018-12-07 18:24 UTC by jsdelivrbot

[RawGit](https://rawgit.com/) is shutting down. This PR replaces all RawGit links with the recommended alternative - [jsDelivr](https://www.jsdelivr.com/). jsDelivr is a free and fast open source CDN hosting all files from GitHub and npm.

*This is an automated PR which is meant to make the migration process as easy as possible. If something doesn't look right or you have any questions, feel free to ping MartinKolarik or jimaek in this PR. You may also use our [online migration tool](https://www.jsdelivr.com/rawgit) to convert other RawGit links to jsDelivr links.*

2019-09-05 00:24 UTC, javier-lopez commented
Once RawGit is shutdown minos-static will require a valid place from where to fetch [static-get](https://github.com/minos-org/minos-static/blob/master/static-get) both, from http / https in order to make it compatible with bare minimal curl / wget versions that doesn't necessary support ssl, options are welcome

2019-09-05 00:25 UTC, javier-lopez requested changes
This is not a valid replacement, jsDelivr only supports https, the http endpoint redirects to https

2020-03-07 14:32 UTC, divinity76 commented
well it was saturday, and i was bored, made this: https://github.com/loltek/rawgit.loltek.net /  https://rawgit.loltek.net/

is that a valid replacement?

2020-03-07 23:02 UTC, javier-lopez commented
Hello @divinity76, indeed that's a good replacement!, thank you for your collaboration 🍻 , closing this issue

2020-03-07 23:02 UTC, closed without merging