Added install function to static-get
minos-org/minos-static pull request #14
Opened 2019-09-04 21:02 UTC by the-djdj

Added the ability to tell static-get to install a downloaded and extracted package.

2019-09-05 00:17 UTC, javier-lopez requested changes
Thank you for your collaboration 🍻 , I've left a short code review, also, would you consider adding some test cases for the new functionality?, https://github.com/minos-org/minos-static/blob/master/tests/tests.db

Have a nice day!

2019-09-05 00:17 UTC, javier-lopez commented on static-get
> +                        ${compress_bin} < "../${_sget__bfile}"  | tar xf -) && \
Not really sure about the `&& \` at the end of this line, I think it's unclear at best

2019-09-05 00:17 UTC, javier-lopez commented on static-get
> +                        _mkdir_p "${directory}/${_sget__bfile%%.tar*}"
This code seems similar to the one in extract, do you think is it worth to create a function in order to reuse code?

2019-09-05 08:49 UTC, the-djdj commented
The issues should be fixed now. I couldn't figure out how to write a test case that invoked superuser privileges, so the tests focus on lack of write access to root.

2019-09-05 15:25 UTC, merged

2019-09-10 10:23 UTC, maximbaz commented
Nice feature! It would have been nice if we could configure a prefix, i.e. instead of installing to `/bin/` to be able to install to `/opt/bin/`

2019-09-10 14:31 UTC, the-djdj commented
I'll take a look at that, @maximbaz